-- Enable the UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- *** Table: profiles ***
-- (Optional but recommended) This table mirrors the auth.users table for public profile data
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- *** Table: chat_messages ***
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text,
  role text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.chat_messages enable row level security;

-- Policy: Users can view their own messages
create policy "Users can view their own messages"
on public.chat_messages for select
using ( auth.uid() = user_id );

-- Policy: Users can insert their own messages
create policy "Users can insert their own messages"
on public.chat_messages for insert
with check ( auth.uid() = user_id );


-- *** Table: subscriptions ***
create table public.subscriptions (
  user_id uuid references auth.users primary key,
  status text,
  plan_id text,
  current_period_end timestamp with time zone
);

-- Enable RLS
alter table public.subscriptions enable row level security;

-- Policy: Users can view their own subscription
create policy "Users can view their own subscription"
on public.subscriptions for select
using ( auth.uid() = user_id );

-- Policy: Users can update/insert their own subscription (For this demo app logic)
create policy "Users can manage their own subscription"
on public.subscriptions for all
using ( auth.uid() = user_id );
